development:
  adapter: sqlite3
  database: db/locations_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/locations_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/locations_production.sqlite3
  pool: 5
  timeout: 5000
